name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate coverage report
        run: |
          pip install -r requirements.txt
          pip install coverage
          coverage run -m unittest discover -s tests/ -p "test_*.py"
          coverage xml
          
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml
