name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with pytest
        run: python -m unittest discover
        
#       - name: Generate coverage report
#         run: |
#           python -m unittest discover -p "test_*.py"
#          pip install coverage
#          coverage run -m unittest discover -p "test_*.py"
#          coverage xml
          
#       - name: Upload coverage to Codecov
#         uses: codecov/codecov-action@v2
#         with:
#           files: ./coverage.xml
